In [1]:
import numpy as np
from numpy import linalg
import pandas as pd

**Задание 1**
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
N = 10
np.arange (N-1, 0 - 1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
# так наверно лучше
N = 10
np.arange (10) [10::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [4]:
arr = np.arange (25) [25::-1]
arr = arr.reshape(5,5)
print (arr)
np.trace(arr)

[[24 23 22 21 20]
 [19 18 17 16 15]
 [14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]


60

**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.


In [43]:
movies = pd.merge(pd.read_csv('ratings.csv'), pd.read_csv('movies.csv'))
movies['title'].value_counts(5.0).head(1) # ответ: Forrest Gump

Forrest Gump (1994)    0.003263
Name: title, dtype: float64

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.


In [17]:
data_countries = pd.read_csv('power.csv')
(
data_countries[ data_countries['country'].str.contains('lat', case=False) | 
data_countries['country'].str.contains('lit', case=False)| 
data_countries['country'].str.contains('est', case=False) ]['country'].unique()
) #это просто проверка названий, чтобы не рыть весь датафрейм

array(['Lithuania', 'Latvia', 'Estonia', 'State of Palestine',
       'Timor-Leste'], dtype=object)

In [44]:
data_pribaltiki = data_countries[(data_countries['country'] == 'Lithuania') | (data_countries['country'] == 'Estonia') |(data_countries['country'] == 'Latvia')]
data_pribaltiki = data_pribaltiki[(data_pribaltiki['year'] >= 2005) & (data_pribaltiki['year'] <= 2010)]
data_pribaltiki = data_pribaltiki[(data_pribaltiki['quantity'] >= 0)]
data_pribaltiki = data_pribaltiki [(data_pribaltiki ['category'] == 4) | (data_pribaltiki ['category'] == 12) | (data_pribaltiki ['category'] == 21) ]
data_pribaltiki.groupby ('country').sum()

year  quantity  category
country                              
Estonia    198714   63440.0      1620
Latvia     184710   54844.0      1728
Lithuania  435667  122296.0      3330

**Задание 5**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [38]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array ([4, 12, -3])

In [39]:
linalg.solve (a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [48]:
np.allclose (np.dot(a, linalg.solve(a, b)), b)

True